SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM WORKER)
UNION
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM WORKER
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM WORKER)
ORDER BY  TYPE DESC;