SELECT CLIENT.NAME, COUNT(PROJECT.ID) AS PROJECT_COUNT
FROM PROJECT
LEFT JOIN CLIENT
ON CLIENT.ID = PROJECT.CLIENT_ID
GROUP BY CLIENT.NAME
HAVING PROJECT_COUNT = (SELECT MAX(c) FROM  (SELECT CLIENT_ID, COUNT(CLIENT_ID) AS C FROM PROJECT GROUP BY CLIENT_ID));
