SELECT PROJECT_ID, SUM(worker.SALARY)*DATEDIFF(MONTH, START_DATE, FINISH_DATE) AS PRICE
FROM project_worker 
LEFT JOIN worker ON WORKER.ID = project_worker.WORKER_ID
LEFT JOIN PROJECT ON PROJECT.ID =project_worker.PROJECT_ID
GROUP BY PROJECT_ID
ORDER BY PRICE DESC
